default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: postgres
  # user: postgres

development:
  <<: *default
  database: secret_friend_development

test:
  <<: *default
  database: secret_friend_test

production:
  <<: *default
  database: secret_friend_production